name: CI

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master
#  schedule:
#    # run every Monday at 5am UTC
#    - cron: '0 5 * * 1'

jobs:

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
#    needs: cancel_ci
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: First check
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: docs build
            os: ubuntu-latest
            python: 3.8
            toxenv: build_docs
            toxargs: -v

          - name: oldest dependencies
            os: ubuntu-latest
            python: 3.5
            toxenv: py36-test-oldestdeps
            toxargs: -v

          - name: Python 3.7 with all optional dependencies (MacOS X)
            os: macos-latest
            python: 3.7
            toxenv: py37-test-alldeps
            toxargs: -v

          - name: Python 3.9 with coverage
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-cov
            toxargs: -v

          - name: Python 3.8 and disabling optional dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test-core_only
            toxargs: -v

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: contains(matrix.toxenv,'-cov')
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  egg_info:
    name: egg_info with Python 3.7
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run egg_info
      run: python setup.py egg_info