name: CI

on:
  [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: First check
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: docs build
            os: ubuntu-latest
            python: 3.8
            toxenv: build_docs
            toxargs: -v

          - name: oldest dependencies
            os: ubuntu-latest
            python: 3.6
            toxenv: py36-test-oldestdeps
            toxargs: -v

          - name: Python 3.7 with all optional dependencies (MacOS X)
            os: macos-latest
            python: 3.7
            toxenv: py37-test
            toxargs: -v

          - name: Python 3.9 with coverage
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-cov
            toxargs: -v

          - name: Python 3.8 and disabling optional dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test-core_only
            toxargs: -v

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: contains(matrix.toxenv,'-cov')
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
